name: Publish
permissions:
  contents: write
on:
  push:
    branches:
      - main
jobs:
  publish-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.17"
      - name: Install
        run: npm install
      - name: Build markdown site
        run: npm run docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: _site
          git-config-name: GitHub Actions 
          git-config-email: ghactions@example.com
